# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               Stochastic Stuff by Pavel Dmytrenko
tagline:             ''
url:                 http://pavdmyt.com/
description:         'A place for Python, Math and maybe Science Fiction.'
paginate:            3

# About/contact
author:
  name:              'Pavel Dmytrenko'
  url:               ''

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/pavdmyt/pavdmyt.github.io
