# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               Stochastic Stuff
tagline:             ''
url:                 http://pavdmyt.com
description:         'A place for Python, Math and maybe Science Fiction.'
paginate:            10

# About/contact
author:
  name:              'Pavel Dmytrenko'
  email:             'mail@pavdmyt.com'
  url:               ''

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/pavdmyt/pavdmyt.github.io

excerpt_separator:   <!--more-->
